from sentence_transformers import SentenceTransformer, util
import numpy as np

model = SentenceTransformer('stsb-roberta-large')

sentences = [
  "I like python.",
  "lag",
  "Last update my swipe lock screen keeps disappearing and I have to put my password back in even though I have it set for the swipe screen",
  "SureSwipe quit working. I can log in and turn it back on and it will work once, but then the next time I'm forced to use my password.",
  "It's a decent app, but signing in is a pain sometimes. I chose finger swipe, but it keeps asking for my password every login.",
  "Great app and bank, can't seem to get it to recognize my Sure Swipe login for the app unless I manually reset it every time I go into the app.",
  "Recent update has made it all but impossible to use sure swipe to log in. I can still get in with my password, and I can manually reset my log in to sure swipe, but it only works one time afterwards, so I have to constantly reset my security options. Please fix this soon, it is a major hassle in an otherwise good app.",
  "New review 5/2: Signing in with your pattern or preference no longer works, at a glance no longer works, the card lock seems to show up when it feels like it. The development of this app is so lazy and untested, it's ridiculous.",
  "Pattern sign-in is deactivating. I have this feature turned on, but whenever I launch the app, it takes me to the username/password screen and doesn't give me the option of singing in with a pattern :(",
  "App keeps on changing my sign in from sure swipe to password which i dont like..i keep on changing it in d settings but it keeps on changing from d sureswipe to password provision,which is annoying..they should work on it",
  "Recent changes have broken the Sure Swipe login capability. Entering a very secure password everytime is onerous, and the fingerprint doesn't work on my phone. App is generally fine otherwise, except for the constant upselling messages.",
  "Always loved this app until recently. I'm not able to open app with security swype any longer. I have to enter my password each time. I go back and forth with another app for work and each time I have to sign in again using pw. Incredibly annoying and disappointing.",
  "Sureswipe pattern no longer works. Login is no longer easy. Why do I need this app if I have to type my password in every single time ??? The website is way easier to log into because at least my pw is saved. This is my only credit card app that actually makes me type in my password every single time, all the others have some easy form of login method.",
  "It was great until the latest update. It ruined the ability for the pattern swipe. You can force it to work once if you reset your swipe but then reverts right back to forcing you to use a password",
  "Great for making payments but I am really disappointed that the pattern swipe option is gone. I am terrible with remembering passwords.",
  "All of a sudden the app is constantly asking for my password when I have had Swipe set as my login. I never save my passwords and have them written down at home. Meaning I have to go home to find out my password. Please fix!",
  "The only way it is letting me sign in, is pasword, when i put for a different way yo sign in, also, i had to uninstall and reinstall inorder for the app to work again.",
  "Since the last update, sure swipe doesn't work to log me in anymore. If I try to reset it, it gives me an error message. It also gives me daily pop ups to download their capital one shopping app... that I already have, and downloaded from a prompt in this app. Otherwise it's user friendly.",
  "I am happy with the app overall. I do not like that my sureswipe sign in setting keeps changing back to password sign in.",
  "Recent update disables sureswipe until you manually enable it, and even then after a few hours/1 day it disables sureswipe",
  "I used to like the app but since the last update i cant use my sign in swipe, it always takes me back to my password. Why???",
  "No way to unlink old accounts with open accta per c.s., so every time I log in, I get the error message that the app has trouble getting all my acct info, & that error will never go away. I have no way of selecting go paperless on the app, but all my credit cards apps do. I have to use the website for some options which is super hard to do since I only have a phone. Not as convenient as it could be. Otherwise, it is easy to log in and see my current available. *Sureswipe no longer works.*",
  "Suddenly it isn't using biometric sign-in and not saving it when I try to update. Your app update messes up my access. Very Frustrating.",
  "Good app. Aggravating the swipe to signin basically quit working and have to manually put in password almost every time.",
  "Used to love the app, but since switching to a Galaxy s23 Ultra the password swipe works once and then I have to manually log in.",
  "Why would you get rid of the swipe feature just to force a fingerprint??",
  "Updated the app. Forced me to sign in with my login instead of my pattern. Even ensuring the SureSwipe is active and resetting the pattern doesn't help.",
  "Worked great until they took away the sure swipe login. I have to type in my password everytime I go on since my phone doesn't do fingerprints",
  "Idk what happened maybe during the last couple of updates but now lately I have to continuously put in my physical password because the app forgets I have swipe sign in set up but doesn't let me everytime I load up the app I have to put in my password, please fix this it's very annoying.",
  "After recent update, is no longer allowing selected sign-in options like sureswype. have to use password every time, unless I've just reset my pattern. app login has become broken.",
  "I set up my login as the pattern swipe, but every time I open the app, I have to put in my password. I can't even tell you how aggravating that is, when it used to work perfectly every time.",
  "After update swipe pattern no longer works real pain having to use passwords every single time.",
  "Why can't i swipe to get in anymore?",
  "Ok app but the login method I chose keeps switching itself back to typing in my password all of a sudden. It never used to do that.",
  "To slow, what happened to quick view with sure swipe , somewhere there other time need password, this app really SUCKS, Too many added to check my account.!!!!!",
  "Lately the sign-in options have stopped working for me. I set it to sureswipe and reset my pattern; now the app only allows me to sign in using my password. This is not only inconvenient but suspicious. I've tried to fix several times but each time I log out I'm prompted for the password. Ridiculous after years off working without a single issue.",
  "You forced me to update the app, now I can no longer use sure swipe open the app, when I try to report the issue using feedback in the app, I get the message oh sorry looks like we hit a snag try again...every. single. time.",
  "Update: it used to be awesome. For some idiotic reason, even though I have set up a swipe pattern for easier access, and set that pattern as my preferred method, most of the time when I open the application I have to enter my password for it to open. It is so very stupid. If an IT professional from cap one wants to get back with me about ensuring a guaranteed 100% ability to use my swipe pattern every time I will change my review. Awesome! Love the new graphics and user interface!",
  "Easy to navigate however ever since the last update I have to sign in with my password instead of my swipe password even though my sipe to sign in is selected. I even reset it multiple times and everytime it'll work once and once I hit sign out its back to using password.. it's quite annoying!",
  "Since the last update, my sure swipe doesn't work. Grrr!!",
  "Did not like how last update removed my sign on password and now i have to manually log in like I'm on the website. What's the point? I think i might Uninstall and use the website since I'm stuck putting in a password everytime now! I miss my swipe password option!!",
  "I'm getting super frustrated with this app. I have it set to use a swipe password and everytime I go to use this app it asks for my password. Even tho I have it set to remember me. Even tho I have the swipe set up. It worked perfectly a month ago. Undo whatever you did and fix it.",
  "Easy to use and loved the swipe login that doesn't seem to work after the last update unfortunately",
  "lately my sign in method has not been consistent... requiring password suddenly when all prior use has been with swipe pattern, and even after manually verifying swipe setting was active it went back to asking for password unless i set it to use fingerprint. bizarre, and frustrating.",
  "There is something wrong with my app. I'm not sure if others are having this same issue ? Every time I go to sign in, it brings me back to the password every time I sign in when I have in the security sign in to use a swipe mode box checked",
  "Can't do the preview anymore. Pattern log in no longer works",
  "Have to keep typing in my pass code even though I set up the swipe method very frustrating",
  "After update I have to login every time I want to use the app. Swipe was taken away, bring it back",
  "Sure swipe option reverts back to password entry after one try. Motorola moto g power on Android 11.",
  "The pattern sign in not working properly after the last 2 app updates. It is set on in the app and I reset the pattern as troubleshooting but it still doesn't work. I get it to work when I sign in with the password, turn off the pattern feature and back on, and sign back in. It works that one time and then goes back to password sign in. I am on a Samsung 10 on the latest firmware/OS update.",
  "Why did you remove the swype option for log in and replace with a fingerprint or password? I am thinking of switching up my accounts...",
  "Swipe password not allowed anymore?!",
  "It's been a really good app for the most part. I'm glad that there is very little I actually have to go onto the website for because most everything is in the app. A recent update, causing me inconvenience, is what drops my rating to a 3. My ability to use swipe to access my accounts disappeared with an update a few weeks ago. I confirm it's still set, have reset it, still can't use it. Gotta enter my password now on my Samsung 22 Ultra.",
  "It used to be 5 star but now it logs me out everytime I'm not using it even though I chose the finger swipe pattern thing, and I hate it. I hate it so much I won't even use my Capital One cards anymore. I use my Verizon Visa, they gave me a 7500 limit unlike Capital One who haven't even got me over 1000 even though I've had these cards for years. Junk.",
  "The pattern sign-in is broken. Please fix. It won't stay set",
  "Swipe login has been broken for weeks.",
  "If I select the sure swipe login in option or works for a short time and constantly reverts back to a password login. Very annoying.",
  "Keeps making me sign in instead of allowing me to sign in with diagram which is my preferred sign in",
  "It suddenly stopped using my swipe login, asking me for a password everytime, even though the swipe login is still turned on in the settings",
  "Used to be great, now it requires my password every time although I have my swipe pattern set & have used it for years. The sign on screen now gives two options, password or fingerprint. But inside the app the function to reset your swipe is still there & functioning. I did not change a thing so why is this happening? From reading other reviews many others are also experiencing this so HELLO app developers! Anyone care to respond or fix this??? I just updated the app, same issue persists!",
  "Had sure swipe set up. The app for some reason decides it's not my preferred sign in method. This really makes ease of use and accessibility very poor.",
  "I can no longer log in with gestures",
  "Used to be able to sign in with swine, now it requires typing a password every time. Not a fan, lol.",
  "Lately the system is acting crazy. .The swipe method of logging in is not popping up.",
  "The app itself is fine, but the swipe login is busted, no matter how many times I reset it it just doesn't work",
  "Even with current app up to date, it's still messing up. It forces me to use finger print or password when I have the sure swipe setup.",
  "After the last 2 updates, the signi in defaults to password use instead of the sureswipe enabled.",
  "Swipe not working still!",
  "Recent update broke swipe sign in. Sometimes even fails to login in with correct password entered. It has been working for years.",
  "1 star until the sureswipe is fixed. I have it turned on, but it keeps making me sign in with my password instead. Fix and I'll bring my review up to 5 stars.",
  "use to open my app with a secure swipe..now it's gone..set it up again..still gone",
  "Pattern sign on disappeared, not happy",
  "The app has begun requiring a password on login every single time, even when other options (such as fingerprint or swipe) are selected. It's very frustrating!",
  "Not happy! I used to be able to use a pattern to sign in, but now it always asks for my password! I have my preference set to pattern, but it won't let me sign in that way!",
  "Everytime I sign in I have to put my password instead of the method I prefer and it's pissing me off",
  "Recently this app started asking for my password and will NOT allow me to return to swipe mode, which I really liked. Finger print function on my S22 Ultra I can't use as I am a dishwasher and my fingerprint is basically useless, so I simply can't use that option. PLEASE ADD SWIPE FUNCTION BACK!! THANK YOU",
  'The swipe login functionality stopped working, and asks for my password every single time I login. When I go to verify my settings, as soon as I get to the sign in options page, the "use sureswipe" appears unselected, and gets selected automatically in front of my eyes. As soon as I logout and try to login again, it goes back to asking for my password. Please fix this.',
  "Update: since the last update this app is very glitch and I have become very concerned about the security. The function to sign in with a fingerprint or swipe works only sometimes. The app closes in the middle of transactions periodically and when I try to use or redeem my awards it will deduct my points but not allow the redemption. Going back to the PC and skipping the app.",
  "I've been having some issues with the app lately. It's asking me to put in my password even though I had selected the swipe setting. It also gives me an error message when I try to log in even though I know the passwprd is right. Please fix this. I've never had any issues before, and I thought it was a different type of issue.",
  "Even when you set it for swiping log in still keeps asking for password",
  "Ever since the last update sure swipe doesn't work anymore. I have it turned on but it keeps making me use my password",
  "Worked ok until recently. Swipe function to log on with pattern is my chosen option yet always seems to ask for password. Log off also functions poorly and is located in an inconvenient place.",
  "lately I have to keep logging into my account. have swipe setup but every time it wants me to enter my password.",
  "I hate that they disabled swipe patterns log in. Forcing ppl to use fingerprint biometrics is cruel, your app and website are going to be used less because of this, I will move my funds out of your institution.",
  "I've been using this app for 6 years, now I can't sign in with the swipe? I have to type my password in each time, and I need access to this multiple times a day to transfer money and deposit checks. What happened to the swipe login ??",
  "No more swipe security, that's not cool.",
  "not able to use the pattern swipe to login although it's what I selected to use.",
  "I'll change the rating once I can use swipe or fingerprint sign-on again... I don't want to type my password every time, it's not efficient and I feel I'm less secure on your app",
  "It freezes up,and the signing in can't use the pattern after choosing that choice",
  "Need my swipe back",
  "Face ID isn’t working. I log in and set it up for next time and it still doesn’t work.",
  "I enjoy this app, but I feel like I am now being forced to use a fingerprint instead of the swipe to log in. I have been set up with the swipe for years now. All of a sudden, it asked me to put in a password each time. I have to manually select swipe under the security tab before I log out each time in order to get the swipe feature when I try to log in again.",
  "I had swipe pattern to unlock and after the last update it continues to ask for my password. Fix this please.",
  "Why does it keep switching back to password from swipe??,",
  "The app used to keep me signed in and have me swipe in a pattern to get to my account. Now the app signs me out of my account then has me input my password every time I want to use it. Annoying!",
  "Since last update, I can't sign in with Sure Swipe, even though I have it set as my preferred method of signing in, makes me use password.",
  "My score used to be a 5 but has gone down to a 3 because the sure swipe logon stopped working. Now I need my password, make sure sure swipe is on, it works once and then disappears when logging off. I tried to write this in the app's feedback, but that doesn't work now either.",
  "I love the SureSwipe login pattern, but it only works once, then it doesn't appear. If I log in the torturous way (PLEASE give me the option of seeing the password!!!) and check, it's enabled, but it won't appear unless I disable it and enable it again. Pixel 6a.",
  "Since last update app keeps requiring pw to login instead the swipe pattern. Please fix this.",
  "Sure swipe not working. Every time I set it. When I go back into the app it reverts to inputting my password. FIX THIS!!!",
  "Whatever change was recently made no longer recognizes my swipe access and requires a password each time. This just started a few days ago. Each time I've logged in I confirm my pattern and that it's selected, but does not default to that option anymore.",
  "Frustrating. Keeps asking me to use password instead of the swipe feature saved",
  "This used to be a good app. Now it won't let me sign in with the swipe pattern. It makes me type my password every single time. Annoying",
  "Since recent update swipe sign in doesn't work.",
  "Does what I need but, after update it stops allowing me to use just the swipe method of logging in. It seems to want me to do thumbprint which I don't want. I really don't want to go back to just the website.",
  "Most recent update affected my sure swipe login and now it won't stay on that option and makes me use password. They need to fix that glitch.",
  "Can no longer sign-in quickly using pattern!! Just user name/password. And 'yes', I made sure my security sign-in was still set to 'pattern' after update.",
  'The most recent update violently broke parts of the app. The swipe access no longer works even after resetting the pattern. I must use a password everytime now. The apps "report a bug" feature and "submit suggestion" no longer work, and so this review appears to be the only way to communicate with capital one. Please undo the last update, or at least fix these bugs.',
  "Every time I use it now, it asks for a password instead of using the pad lock dots.",
  "This latest update is horrible. You can't sign in with your pattern, no quick view of your account. Please go back to the last version.",
  "Good app to see accounts in one place, but recent update no longer allows my swipe option for log in to work. It claims it does and I have that option selected, but it doesn't work. Makes me use my password for log in. Please fix!!",
  "The last update caused the sign-in setting to no longer save. I use the swipe pattern to sign in. Once I log out the sign-in resets to password.",
  "Since updating, I've had an issue where Sure Swipe won't stay activated. It'll show in the security menu as active, but it keeps having me sign in using my password. If I turn the feature off and back on it'll work for the next log on, but then it'll stop working again if I don't do this every single time",
  "I can no longer sign in with the swipe pattern like I've done for years on the app. I sign in with my password and then change the setting to the swipe pattern every single time (it's already on but I turn it off and then back on again to make sure it's selected), but the next time I log in I still have to use my password again. This has been going on for weeks now and it's very annoying...",
  "The app changed overnight it will no longer allow me to use the finger swipe option to log in. I never asked for this change it. I had to delete the app.",
  "Too many bugs....swipe to sign in hasn't worked in months.",
  "can no longer sign in with a pattern. now is just password or fingerprint.",
  "The order of my accounts keeps changing. I’ve reordered the accounts several times in the preferences. It sometimes works, but then reverts next time I open the app",
]

sentence1 = input("Please enter a string: ")
for sentence in sentences:
    embedding1 = model.encode(sentence1, convert_to_tensor=True)
    embedding2 = model.encode(sentence, convert_to_tensor=True)
    # compute similarity scores of two embeddings
    cosine_scores = util.pytorch_cos_sim(embedding1, embedding2)
    if (cosine_scores.item() > 0.2):
        print("Sentence 2:", sentence)
        print("Similarity score:", cosine_scores.item())